on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 0 * * *'

jobs:
  build-and-release:
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depthdepth: 0

      - name: Build packages
        run: ./build.sh

      - name: Release
        run: ./release.sh
